const fallbackWeapons=[{id:1,name:'M4',category:'Assault Rifle',icon:'https://placehold.co/500x500/17111f/a855f7?text=M4',image:'https://placehold.co/900x500/100c16/c084fc?text=M4+BUILD',attachments:['Monolithic Suppressor','OWC Marksman','No Stock','50 Round Mag','Granulated Grip']},{id:2,name:'Kilo 141',category:'Assault Rifle',icon:'https://placehold.co/500x500/17111f/a855f7?text=KILO',image:'https://placehold.co/900x500/100c16/c084fc?text=KILO+BUILD',attachments:['Monolithic Suppressor','OWC Marksman','RTC Steady Stock','Large Extended Mag','Granulated Grip']},{id:3,name:'DL Q33',category:'Sniper',icon:'https://placehold.co/500x500/17111f/a855f7?text=DLQ',image:'https://placehold.co/900x500/100c16/c084fc?text=DLQ+BUILD',attachments:['MIP Light','OWC Laser','Skeletal Stock','Extended Mag','Stippled Grip']}];
const fallbackConfigs=[{id:1,title:'HUD Code',type:'HUD',description:'Import your custom HUD layout.',code:'7A8B-2C91-44FE-9D21'},{id:2,title:'Sensitivity',type:'Sensitivity',description:'Fast multiplayer sensitivity setup.',code:'SENS-92A1-77BC-51DD'},{id:3,title:'Graphics / Color',type:'Graphics',description:'Graphics and color configuration.',code:'GFX-PL8R-2026-77XZ'}];
let weapons=[],configs=[],news=[],builds=[],category='All';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t='Copied to clipboard'){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
async function copyCode(code){try{await navigator.clipboard.writeText(code);toast()}catch{toast('Copy failed')}}
function renderFilters(){const cats=['All',...new Set(weapons.map(w=>w.category).filter(Boolean))];$('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderFilters();renderWeapons()})}
function renderWeapons(){const q=$('#search').value.toLowerCase();const list=weapons.filter(w=>{const text=`${w.name||''} ${w.category||''} ${(w.attachments||[]).join(' ')}`.toLowerCase();return(category==='All'||w.category===category)&&text.includes(q)});$('#weaponGrid').innerHTML=list.map((w,i)=>`<article class="weapon-card" data-weapon-index="${i}"><button class="weapon-image-trigger" type="button" aria-label="Open ${esc(w.name)} build"><img src="${esc(w.icon||w.image||'https://placehold.co/700x500?text=GUN')}" alt="${esc(w.name)}"></button><div class="weapon-body"><div class="weapon-name">${esc(w.name)}</div><div class="weapon-cat">${esc(w.category||'Weapon')}</div><div class="attachments">${(w.attachments||[]).map(a=>`<span class="tag">${esc(a)}</span>`).join('')}</div><button class="copy" data-copy="${esc((w.attachments||[]).join(' | '))}">COPY BUILD</button></div></article>`).join('');$('#weaponEmpty').style.display=list.length?'none':'block';document.querySelectorAll('.weapon-image-trigger').forEach((btn,i)=>btn.onclick=()=>openWeaponModal(list[i]))}
function openWeaponModal(w){const modal=$('#weaponModal');$('#weaponModalImage').src=w.image||w.icon||'https://placehold.co/900x600?text=BUILD';$('#weaponModalImage').alt=`${w.name} build`;$(`#weaponModalTitle`).textContent=w.name;$('#weaponModalCategory').textContent=w.category||'WEAPON BUILD';$('#weaponModalAttachments').innerHTML=(w.attachments||[]).map(a=>`<span class="tag">${esc(a)}</span>`).join('');$('#weaponModalCopy').dataset.copy=(w.attachments||[]).join(' | ');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}
function closeWeaponModal(){const modal=$('#weaponModal');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function renderConfigs(){$('#configGrid').innerHTML=configs.map(c=>`<article class="config-card"><div class="weapon-cat">${esc(c.type||'CONFIG')}</div><h3>${esc(c.title)}</h3><p>${esc(c.description||'')}</p><div class="code">${esc(c.code)}</div><button class="copy" data-copy="${esc(c.code)}">COPY CODE</button></article>`).join('')}
function renderNews(){$('#newsGrid').innerHTML=news.map(n=>`<article class="news-card">${n.image_url?`<img src="${esc(n.image_url)}" alt="">`:''}<div class="news-body"><small>${new Date(n.published_at).toLocaleDateString()}</small><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p></div></article>`).join('')||'<div class="empty show">No news yet.</div>'}
function renderBuilds(){$('#buildGrid').innerHTML=builds.map(b=>`<article class="build-card">${b.image_url?`<img src="${esc(b.image_url)}" alt="${esc(b.title)}">`:''}<div class="build-body"><small>FEATURED BUILD${b.weapons?.name?' • '+esc(b.weapons.name):''}</small><h3>${esc(b.title)}</h3><p>${esc(b.description||'')}</p>${b.config_code?`<div class="code">${esc(b.config_code)}</div><button class="copy" data-copy="${esc(b.config_code)}">COPY BUILD</button>`:''}</div></article>`).join('')||'<div class="empty show">No featured builds yet.</div>'}
function applySettings(s){if(!s)return;if(s.site_name)document.querySelectorAll('.siteName').forEach(e=>e.textContent=s.site_name);if(s.tagline)$('#heroTagline').textContent=s.tagline;if(s.hero_text)$('#heroText').textContent=s.hero_text;if(s.accent)document.documentElement.style.setProperty('--purple',s.accent)}
function applySocials(s){if(!s)return;[['fb',s.facebook],['ig',s.instagram],['dc',s.discord],['tt',s.tiktok],['yt',s.youtube]].forEach(([id,url])=>{const e=$('#'+id);if(e){e.href=url||'#';e.style.display=url?'grid':'none'}})}
function renderHeroTikTok(url){const frame=$('#heroTikTok'),btn=$('#heroTikTokBtn');if(!frame)return;if(!url){frame.innerHTML='<div class="video-placeholder">TIKTOK FEATURED POST</div>';if(btn)btn.style.display='none';return}const match=String(url).match(/video\/(\d+)/);const id=match?match[1]:null;if(id){frame.innerHTML=`<iframe src="https://www.tiktok.com/player/v1/${id}?autoplay=1&loop=1&description=1&music_info=1&rel=0" title="Featured TikTok" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" loading="eager"></iframe>`}else{frame.innerHTML='<div class="video-placeholder">INVALID TIKTOK URL</div>'}if(btn){btn.href=url;btn.style.display='inline-flex'}}
async function loadData(){weapons=fallbackWeapons;configs=fallbackConfigs;if(!window.supabaseReady||!window.supabaseClient){renderAll();return}const [w,c,f,n,b,sl,ss]=await Promise.all([supabaseClient.from('weapons').select('*').order('created_at',{ascending:false}),supabaseClient.from('configs').select('*').order('created_at',{ascending:false}),supabaseClient.from('featured_content').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle(),supabaseClient.from('news').select('*').order('published_at',{ascending:false}).limit(6),supabaseClient.from('featured_builds').select('*,weapons(name)').order('created_at',{ascending:false}).limit(6),supabaseClient.from('social_links').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle(),supabaseClient.from('site_settings').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle()]);if(!w.error)weapons=w.data||[];if(!c.error)configs=c.data||[];if(!n.error)news=n.data||[];if(!b.error)builds=b.data||[];if(!sl.error)applySocials(sl.data);if(!ss.error)applySettings(ss.data);if(!f.error&&f.data){const fi=$('#featuredImage');if(f.data.image_url&&f.data.image_enabled===true){fi.innerHTML=`<img src="${esc(f.data.image_url)}" alt="Featured">`;fi.style.display='block'}else{fi.style.display='none'}const v=$('#featuredVideo'),vp=$('#featuredVideoPanel');if(f.data.video_url&&f.data.video_enabled===true){if(vp)vp.style.display='block';v.src=f.data.video_url;v.autoplay=f.data.autoplay!==false;v.muted=f.data.muted!==false;v.loop=f.data.loop!==false;$('#videoPlaceholder').style.display='none'}else{v.removeAttribute('src');v.load();$('#videoPlaceholder').style.display='none';if(vp)vp.style.display='none'}renderHeroTikTok(f.data.tiktok_url)}renderAll()}
function renderAll(){renderFilters();renderWeapons();renderConfigs();renderNews();renderBuilds()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-copy]');if(b)copyCode(b.dataset.copy);if(e.target.closest('[data-close-weapon]'))closeWeaponModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeWeaponModal()});$('#search').addEventListener('input',renderWeapons);$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.theme=document.body.classList.contains('light')?'light':'dark';$('#themeBtn').textContent=document.body.classList.contains('light')?'☀':'☾'};if(localStorage.theme==='light')$('#themeBtn').click();window.addEventListener('supabase-ready',loadData);if(window.supabaseReady!==undefined)loadData();
