-- CODM HUB - Supabase schema
create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.weapons (id bigint generated by default as identity primary key,name text not null,category text not null,icon text,image text,attachments jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
create table if not exists public.configs (id bigint generated by default as identity primary key,title text not null,description text,type text not null default 'HUD',code text not null,created_at timestamptz not null default now());
alter table public.configs add column if not exists type text not null default 'HUD';
create table if not exists public.featured_content (id bigint generated by default as identity primary key,image_url text,image_enabled boolean not null default false,video_enabled boolean not null default false,video_url text,autoplay boolean not null default true,muted boolean not null default true,loop boolean not null default true,tiktok_url text,updated_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.news (id bigint generated by default as identity primary key,title text not null,body text not null,image_url text,published_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.featured_builds (id bigint generated by default as identity primary key,title text not null,weapon_id bigint references public.weapons(id) on delete set null,description text,image_url text,config_code text,created_at timestamptz not null default now());
create table if not exists public.social_links (id bigint generated by default as identity primary key,facebook text,instagram text,discord text,tiktok text,youtube text,updated_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists public.site_settings (id bigint generated by default as identity primary key,site_name text not null default 'CODM HUB',tagline text not null default 'Build. Copy. Dominate.',hero_text text,accent text default '#a855f7',updated_at timestamptz not null default now(),created_at timestamptz not null default now());

alter table public.admin_users enable row level security;
alter table public.weapons enable row level security;
alter table public.configs enable row level security;
alter table public.featured_content enable row level security;
alter table public.news enable row level security;
alter table public.featured_builds enable row level security;
alter table public.social_links enable row level security;
alter table public.site_settings enable row level security;

-- Public reads
drop policy if exists "public read weapons" on public.weapons;
drop policy if exists "public read configs" on public.configs;
drop policy if exists "public read featured" on public.featured_content;
drop policy if exists "public read news" on public.news;
drop policy if exists "public read builds" on public.featured_builds;
drop policy if exists "public read socials" on public.social_links;
drop policy if exists "public read settings" on public.site_settings;
drop policy if exists "admins read own record" on public.admin_users;
drop policy if exists "admins write weapons" on public.weapons;
drop policy if exists "admins write configs" on public.configs;
drop policy if exists "admins write featured" on public.featured_content;
drop policy if exists "admins write news" on public.news;
drop policy if exists "admins write builds" on public.featured_builds;
drop policy if exists "admins write socials" on public.social_links;
drop policy if exists "admins write settings" on public.site_settings;

create policy "public read weapons" on public.weapons for select to anon,authenticated using (true);
create policy "public read configs" on public.configs for select to anon,authenticated using (true);
create policy "public read featured" on public.featured_content for select to anon,authenticated using (true);
create policy "public read news" on public.news for select to anon,authenticated using (true);
create policy "public read builds" on public.featured_builds for select to anon,authenticated using (true);
create policy "public read socials" on public.social_links for select to anon,authenticated using (true);
create policy "public read settings" on public.site_settings for select to anon,authenticated using (true);
create policy "admins read own record" on public.admin_users for select to authenticated using (user_id = auth.uid());

-- Admin writes
create policy "admins write weapons" on public.weapons for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write configs" on public.configs for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write featured" on public.featured_content for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write news" on public.news for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write builds" on public.featured_builds for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write socials" on public.social_links for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
create policy "admins write settings" on public.site_settings for all to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

-- Prevent duplicate policies if re-running: drop/recreate safely
-- If this script has already been run once, execute the DROP POLICY statements below before the CREATE POLICY statements above.
-- Admin setup:
-- 1. Authentication > Users > Add user.
-- 2. Copy the UUID.
-- 3. INSERT INTO public.admin_users(user_id) VALUES ('YOUR-USER-UUID');

-- Existing projects: run these if featured_content already exists
alter table public.featured_content add column if not exists image_enabled boolean not null default false;
alter table public.featured_content add column if not exists video_enabled boolean not null default false;
alter table public.featured_content add column if not exists tiktok_url text;


-- TikTok player autoplay
alter table public.featured_content add column if not exists tiktok_autoplay boolean not null default true;
