const $=s=>document.querySelector(s);let client=null,isAdmin=false,currentUser=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function status(id,msg,type=''){const e=$(id);if(e){e.textContent=msg;e.className=`status ${type}`.trim()}}
function db(msg,type=''){const e=$('#dbStatus');e.textContent=msg;e.className=`db-status ${type}`.trim()}
async function boot(){if(!window.supabaseReady){status('#loginStatus','Supabase is not configured. Update supabase.js.','error');return}client=window.supabaseClient;const {data:{session}}=await client.auth.getSession();await handleSession(session);client.auth.onAuthStateChange((_e,s)=>handleSession(s))}
async function handleSession(session){if(!session){isAdmin=false;$('#loginPanel').hidden=false;$('#dashboard').hidden=true;return}const {data,error}=await client.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(error||!data){await client.auth.signOut();status('#loginStatus','This account is signed in, but it is not an authorized admin.','error');return}currentUser=session.user;isAdmin=true;$('#loginPanel').hidden=true;$('#dashboard').hidden=false;$('#userEmail').textContent=session.user.email||'';$('#accountEmail').textContent=session.user.email||'';db('● Supabase connected — admin access verified','ok');await renderAll()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=$('#loginBtn');b.disabled=true;b.textContent='SIGNING IN…';status('#loginStatus','');const {error}=await client.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error)status('#loginStatus',error.message,'error');b.disabled=false;b.textContent='LOGIN'};
async function renderAll(){if(!isAdmin)return;await Promise.all([renderWeapons(),renderConfigs(),renderFeatured(),renderNews(),renderBuilds(),renderSocials(),renderSettings()])}
async function renderWeapons(){const {data,error}=await client.from('weapons').select('*').order('created_at',{ascending:false});$('#adminWeapons').innerHTML=error?`<p class="error-text">${esc(error.message)}</p>`:(data||[]).map(w=>`<div class="item"><span><strong>${esc(w.name)}</strong><small> ${esc(w.category)}</small></span><button class="delete" data-del="weapons" data-id="${w.id}">Delete</button></div>`).join('')||'<p class="muted">No weapons yet.</p>';$('#bWeapon').innerHTML='<option value="">No linked weapon</option>'+(data||[]).map(w=>`<option value="${w.id}">${esc(w.name)}</option>`).join('')}
async function renderConfigs(){const {data,error}=await client.from('configs').select('*').order('created_at',{ascending:false});$('#adminConfigs').innerHTML=error?`<p class="error-text">${esc(error.message)}</p>`:(data||[]).map(c=>`<div class="item"><span><strong>${esc(c.title)}</strong><small> ${esc(c.type||'')}</small></span><button class="delete" data-del="configs" data-id="${c.id}">Delete</button></div>`).join('')||'<p class="muted">No configs yet.</p>'}
async function renderFeatured(){const {data}=await client.from('featured_content').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();if(data){fImage.value=data.image_url||'';fImageEnabled.checked=data.image_enabled===true;fVideo.value=data.video_url||'';fVideoEnabled.checked=data.video_enabled===true;fTikTok.value=data.tiktok_url||'';fTikTokAutoplay.checked=data.tiktok_autoplay!==false;fAutoplay.checked=data.autoplay!==false;fMuted.checked=data.muted!==false;fLoop.checked=data.loop!==false}$('#featuredPreview').innerHTML=data?.video_url&&data?.video_enabled?`<video src="${esc(data.video_url)}" controls ${data.autoplay?'autoplay':''} ${data.muted?'muted':''} ${data.loop?'loop':''} playsinline></video>`:data?.image_url&&data?.image_enabled?`<img src="${esc(data.image_url)}">`:'<span class="muted">No featured media enabled.</span>'}
async function renderNews(){const {data,error}=await client.from('news').select('*').order('published_at',{ascending:false});$('#adminNews').innerHTML=error?`<p class="error-text">${esc(error.message)}</p>`:(data||[]).map(n=>`<div class="item"><span><strong>${esc(n.title)}</strong><small>${new Date(n.published_at).toLocaleDateString()}</small></span><button class="delete" data-del="news" data-id="${n.id}">Delete</button></div>`).join('')||'<p class="muted">No news yet.</p>'}
async function renderBuilds(){const {data,error}=await client.from('featured_builds').select('*,weapons(name)').order('created_at',{ascending:false});$('#adminBuilds').innerHTML=error?`<p class="error-text">${esc(error.message)}</p>`:(data||[]).map(b=>`<div class="item"><span><strong>${esc(b.title)}</strong><small>${esc(b.weapons?.name||'')}</small></span><button class="delete" data-del="featured_builds" data-id="${b.id}">Delete</button></div>`).join('')||'<p class="muted">No featured builds yet.</p>'}
async function renderSocials(){const {data}=await client.from('social_links').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();if(data){sFacebook.value=data.facebook||'';sInstagram.value=data.instagram||'';sDiscord.value=data.discord||'';sTikTok.value=data.tiktok||'';sYoutube.value=data.youtube||''}}
async function renderSettings(){const {data}=await client.from('site_settings').select('*').order('created_at',{ascending:false}).limit(1).maybeSingle();if(data){siteName.value=data.site_name||'';siteTagline.value=data.tagline||'';siteHero.value=data.hero_text||'';siteAccent.value=data.accent||'#a855f7'}}
$('#weaponForm').onsubmit=async e=>{e.preventDefault();const {error}=await client.from('weapons').insert({name:wName.value.trim(),category:wCat.value.trim(),icon:wIcon.value.trim()||null,image:wImage.value.trim()||null,attachments:wAttach.value.split('\n').map(x=>x.trim()).filter(Boolean)});if(error)return status('#weaponStatus',error.message,'error');e.target.reset();status('#weaponStatus','Weapon saved to Supabase.','success');await renderWeapons()};
$('#configForm').onsubmit=async e=>{e.preventDefault();const {error}=await client.from('configs').insert({title:cTitle.value.trim(),type:cType.value,description:cDesc.value.trim()||null,code:cCode.value.trim()});if(error)return status('#configStatus',error.message,'error');e.target.reset();status('#configStatus','Config saved.','success');await renderConfigs()};
$('#featuredForm').onsubmit=async e=>{e.preventDefault();const old=await client.from('featured_content').select('id').order('created_at',{ascending:false}).limit(1).maybeSingle();const payload={image_url:fImage.value.trim()||null,image_enabled:fImageEnabled.checked,video_enabled:fVideoEnabled.checked,video_url:fVideo.value.trim()||null,tiktok_url:fTikTok.value.trim()||null,tiktok_autoplay:fTikTokAutoplay.checked,autoplay:fAutoplay.checked,muted:fMuted.checked,loop:fLoop.checked,updated_at:new Date().toISOString()};let r=old.data?await client.from('featured_content').update(payload).eq('id',old.data.id):await client.from('featured_content').insert(payload);if(r.error)return status('#featuredStatus',r.error.message,'error');status('#featuredStatus','Featured content saved.','success');await renderFeatured()};
$('#newsForm').onsubmit=async e=>{e.preventDefault();const {error}=await client.from('news').insert({title:nTitle.value.trim(),body:nBody.value.trim(),image_url:nImage.value.trim()||null});if(error)return status('#newsStatus',error.message,'error');e.target.reset();status('#newsStatus','News published.','success');await renderNews()};
$('#buildForm').onsubmit=async e=>{e.preventDefault();const {error}=await client.from('featured_builds').insert({title:bTitle.value.trim(),weapon_id:bWeapon.value||null,image_url:bImage.value.trim()||null,description:bDesc.value.trim()||null,config_code:bCode.value.trim()||null});if(error)return status('#buildStatus',error.message,'error');e.target.reset();status('#buildStatus','Featured build added.','success');await renderBuilds()};
$('#socialForm').onsubmit=async e=>{e.preventDefault();const old=await client.from('social_links').select('id').order('created_at',{ascending:false}).limit(1).maybeSingle();const p={facebook:sFacebook.value.trim()||null,instagram:sInstagram.value.trim()||null,discord:sDiscord.value.trim()||null,tiktok:sTikTok.value.trim()||null,youtube:sYoutube.value.trim()||null,updated_at:new Date().toISOString()};const r=old.data?await client.from('social_links').update(p).eq('id',old.data.id):await client.from('social_links').insert(p);if(r.error)return status('#socialStatus',r.error.message,'error');status('#socialStatus','Social links saved.','success')};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const old=await client.from('site_settings').select('id').order('created_at',{ascending:false}).limit(1).maybeSingle();const p={site_name:siteName.value.trim()||'CODM HUB',tagline:siteTagline.value.trim()||'Build. Copy. Dominate.',hero_text:siteHero.value.trim()||null,accent:siteAccent.value.trim()||'#a855f7',updated_at:new Date().toISOString()};const r=old.data?await client.from('site_settings').update(p).eq('id',old.data.id):await client.from('site_settings').insert(p);if(r.error)return status('#settingsStatus',r.error.message,'error');status('#settingsStatus','Homepage settings saved.','success')};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-del]');if(!b)return;if(!confirm('Delete this item?'))return;const {error}=await client.from(b.dataset.del).delete().eq('id',b.dataset.id);if(error)alert(error.message);await renderAll()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tabcontent').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
async function logout(){if(client)await client.auth.signOut()}$('#logoutBtn').onclick=logout;$('#accountLogout').onclick=logout;window.addEventListener('supabase-ready',boot);if(window.supabaseReady!==undefined)boot();
